config/routes.rb
Rentdash::Application.routes.draw do
  root to: "listings#index"

  resources :listings
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  validates :title, presence: true
  validates :location, presence: true
  validates :description, presence: true 
  validates :rent, presence: true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController\

  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  def index 
    @listings = Listing.all
  end

  def new 
    @listing = Listing.new
  end

  def create 
    @listing = Listing.new(listing_params)

    if @listing.save
      flash[:notice] = "Listing has been created."
      redirect_to @listing 
    else
      flash[:alert] = "Listing hasn't been created."
      render 'new'
    end
  end

  def show 

  end

  def edit

  end

  def update
    if @listing.update(listing_params)
      flash[:notice] = "Listing has been updated."
      redirect_to @listing 
    else
      flash[:alert] = "Listing has not been updated."
      render 'edit'
    end
  end

  def destroy 
    @listing.destroy
    flash[:notice] = "Listing has been deleted."
    redirect_to listings_path
  end

private
  def listing_params
    params.require(:listing).permit(:title, :location, :description, :rent)
  end

  def set_listing 
    @listing = Listing.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The listing you were looking for cannot be found."
    redirect_to listings_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(*parts)
    unless parts.empty?
      content_for :title do 
        (parts << "RentDash").join(" - ")
      end
    end
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Rentdash", root_path, :class => 'brand' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "RentDash" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rentdash" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </div>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/listings/_form.html.erb
<%= simple_form_for @listing do |f| %>
  <%= f.input :title %>
  <%= f.input :location %>
  <%= f.input :description %>
  <%= f.input :rent %>

  <%= f.button :submit %>

<% end %>

app/views/listings/edit.html.erb
<h2>Edit Listing</h2>
<%= render 'form' %>

app/views/listings/index.html.erb
<h2>Listings</h2>

<div>
  <ul>
    <% @listings.each do |listing| %>
      <li><%= link_to listing.title, listing %></li>
    <% end %>
  </ul>
</div>

<%= link_to "New Listing", new_listing_path %>

app/views/listings/new.html.erb
<h2>New Listing</h2>
<%= render 'form' %>

app/views/listings/show.html.erb
<% title(@listing.title, "Listings") %>
<h2><%= @listing.title %></h2>

<%= link_to 'Edit', edit_listing_path(@listing) %>
<%= link_to 'Delete', listing_path(@listing),
                      method: :delete,
                      data: { confirm: 
                        "Are you sure you want to delete this project? " 
                            } %>